// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: api/uuid-service/v1/errors/uuid.error.v1.proto

package errorv1

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"

	errorv1 "github.com/go-micro-saas/service-api/api/nodeid-service/v1/errors"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort

	_ = errorv1.ERROR(0)
)

// Validate checks the field values on README with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *README) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on README with the rules defined in the
// proto definition for this message. If any rules are violated, the result is
// a list of violation errors wrapped in READMEMultiError, or nil if none found.
func (m *README) ValidateAll() error {
	return m.validate(true)
}

func (m *README) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Error

	if len(errors) > 0 {
		return READMEMultiError(errors)
	}

	return nil
}

// READMEMultiError is an error wrapping multiple validation errors returned by
// README.ValidateAll() if the designated constraints aren't met.
type READMEMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m READMEMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m READMEMultiError) AllErrors() []error { return m }

// READMEValidationError is the validation error returned by README.Validate if
// the designated constraints aren't met.
type READMEValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e READMEValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e READMEValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e READMEValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e READMEValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e READMEValidationError) ErrorName() string { return "READMEValidationError" }

// Error satisfies the builtin error interface
func (e READMEValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sREADME.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = READMEValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = READMEValidationError{}
