// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.8.4
// - protoc             v6.30.2
// source: api/account-service/v1/services/account_event.service.v1.proto

package servicev1

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
	resources "github.com/go-micro-saas/service-api/api/account-service/v1/resources"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationSrvAccountEventV1Ping = "/saas.api.account.servicev1.SrvAccountEventV1/Ping"

type SrvAccountEventV1HTTPServer interface {
	// Ping 身份验证-Ping测试
	Ping(context.Context, *resources.PingReq) (*resources.PingResp, error)
}

func RegisterSrvAccountEventV1HTTPServer(s *http.Server, srv SrvAccountEventV1HTTPServer) {
	r := s.Route("/")
	r.GET("/api/v1/account/event/ping", _SrvAccountEventV1_Ping1_HTTP_Handler(srv))
}

func _SrvAccountEventV1_Ping1_HTTP_Handler(srv SrvAccountEventV1HTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in resources.PingReq
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationSrvAccountEventV1Ping)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.Ping(ctx, req.(*resources.PingReq))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*resources.PingResp)
		return ctx.Result(200, reply)
	}
}

type SrvAccountEventV1HTTPClient interface {
	Ping(ctx context.Context, req *resources.PingReq, opts ...http.CallOption) (rsp *resources.PingResp, err error)
}

type SrvAccountEventV1HTTPClientImpl struct {
	cc *http.Client
}

func NewSrvAccountEventV1HTTPClient(client *http.Client) SrvAccountEventV1HTTPClient {
	return &SrvAccountEventV1HTTPClientImpl{client}
}

func (c *SrvAccountEventV1HTTPClientImpl) Ping(ctx context.Context, in *resources.PingReq, opts ...http.CallOption) (*resources.PingResp, error) {
	var out resources.PingResp
	pattern := "/api/v1/account/event/ping"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationSrvAccountEventV1Ping))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
